extends Node

const ban = preload("res://Assets/WordAudio/ban.mp3")
const bei = preload("res://Assets/WordAudio/bei.mp3")
const bu = preload("res://Assets/WordAudio/bu.mp3")
const dan = preload("res://Assets/WordAudio/dan.mp3")
const dao = preload("res://Assets/WordAudio/dao.mp3")
const de = preload("res://Assets/WordAudio/de.mp3")
const chen = preload("res://Assets/WordAudio/chen.mp3")
const wei = preload("res://Assets/WordAudio/wei.mp3")
const ming = preload("res://Assets/WordAudio/ming.mp3")
const qi = preload("res://Assets/WordAudio/qi.mp3")
const ji = preload("res://Assets/WordAudio/ji.mp3")
const bai = preload("res://Assets/WordAudio/bai.mp3")
const qiang = preload("res://Assets/WordAudio/qiang.mp3")
const di = preload("res://Assets/WordAudio/di.mp3")
const zhao = preload("res://Assets/WordAudio/zhao.mp3") 
const xiang = preload("res://Assets/WordAudio/xiang.mp3")
const xing = preload("res://Assets/WordAudio/xing.mp3")
const xie = preload("res://Assets/WordAudio/xie.mp3")
const du = preload("res://Assets/WordAudio/du.mp3")
const dui = preload("res://Assets/WordAudio/dui.mp3")
const fa = preload("res://Assets/WordAudio/fa.mp3")
const fang = preload("res://Assets/WordAudio/fang.mp3")
const ge = preload("res://Assets/WordAudio/ge.mp3")
const ha = preload("res://Assets/WordAudio/ha.mp3")
const he = preload("res://Assets/WordAudio/he.mp3")
const hou = preload("res://Assets/WordAudio/hou.mp3")
const huan = preload("res://Assets/WordAudio/huan.mp3")
const hui = preload("res://Assets/WordAudio/hui.mp3")
const jiang = preload("res://Assets/WordAudio/jiang.mp3")
const jiao = preload("res://Assets/WordAudio/jiao.mp3")
const jie = preload("res://Assets/WordAudio/jie.mp3")
const jue = preload("res://Assets/WordAudio/jue.mp3")
const kai = preload("res://Assets/WordAudio/kai.mp3")
const kuan = preload("res://Assets/WordAudio/kuan.mp3")
const li = preload("res://Assets/WordAudio/li.mp3")
const lv = preload("res://Assets/WordAudio/lv.mp3")
const mao = preload("res://Assets/WordAudio/mao.mp3")
const men = preload("res://Assets/WordAudio/men.mp3")
const mi = preload("res://Assets/WordAudio/mi.mp3")
const neng = preload("res://Assets/WordAudio/neng.mp3")
const ni = preload("res://Assets/WordAudio/ni.mp3")
const qin = preload("res://Assets/WordAudio/qin.mp3")
const quan = preload("res://Assets/WordAudio/quan.mp3")
const ren = preload("res://Assets/WordAudio/ren.mp3")
const san = preload("res://Assets/WordAudio/san.mp3")
const se = preload("res://Assets/WordAudio/se.mp3")
const shen = preload("res://Assets/WordAudio/shen.mp3")
const shi = preload("res://Assets/WordAudio/shi.mp3")
const shou = preload("res://Assets/WordAudio/shou.mp3")
const shuo = preload("res://Assets/WordAudio/shuo.mp3")
const su = preload("res://Assets/WordAudio/su.mp3")
const ta = preload("res://Assets/WordAudio/ta.mp3")
const te = preload("res://Assets/WordAudio/te.mp3")
const ti = preload("res://Assets/WordAudio/ti.mp3")
const tong = preload("res://Assets/WordAudio/tong.mp3")
const wa = preload("res://Assets/WordAudio/wa.mp3")
const xi = preload("res://Assets/WordAudio/xi.mp3")
const xin = preload("res://Assets/WordAudio/xin.mp3")
const xian = preload("res://Assets/WordAudio/xian.mp3")
const xuan = preload("res://Assets/WordAudio/xuan.mp3")
const yan = preload("res://Assets/WordAudio/yan.mp3")
const yi = preload("res://Assets/WordAudio/yi.mp3")
const yin = preload("res://Assets/WordAudio/yin.mp3")
const you = preload("res://Assets/WordAudio/you.mp3")
const yu = preload("res://Assets/WordAudio/yu.mp3")
const yuan = preload("res://Assets/WordAudio/yuan.mp3")
const zai = preload("res://Assets/WordAudio/zai.mp3")
const zhe = preload("res://Assets/WordAudio/zhe.mp3")
const zhen = preload("res://Assets/WordAudio/zhen.mp3")
const zhi = preload("res://Assets/WordAudio/zhi.mp3")
const zhong = preload("res://Assets/WordAudio/zhong.mp3")
const zhu = preload("res://Assets/WordAudio/zhu.mp3")
const zi = preload("res://Assets/WordAudio/zi.mp3")
const zuo = preload("res://Assets/WordAudio/zuo.mp3")
const error = preload("res://Assets/WordAudio/error.mp3")

func play_pinyin_audio(pinyin:String):
	var pinyin_audio = get(pinyin)
	if pinyin_audio:
		$AudioStreamPlayer2D.stream = pinyin_audio
	else:
		$AudioStreamPlayer2D.stream = error
	$AudioStreamPlayer2D.play()

